
#!/usr/bin/python
# -*- coding: utf-8 -*-

from math import sqrt
"""
 A dictionary of movie critics and their ratings of a small set of movies. Data is collected through a survey conducted among a group
 of friends to find out the interests.
"""
critics = {'Nishanth':
 {'Shawshank Redemption' :4.0,
'Star Wars' :4.5,
'50 Shades of Grey' :2.5,
'The Imitation Game' :4.0,
'Insidious' :4.0,
'Taken series' :3.0,
'Saw Series' :3.0,	
'American Sniper' :4.0,
'Titanic' :3.0,
'Harry Potter Series' :4.0,
'Black Swan' :2.5,
'21 Jump Street' :4.5,
'Fight Club' :4.5,
'Braveheart'  :3.0,
'Lone Survivor' :1.5,
'Horrible Bosses'  :4.5,
'Lord of the Rings' :4.5,
'Sex Tape' :3.0,
'Ouija' :2.0,
'Frozen' :5.0,
'Finding Nemo' :5.0,
'Night at the Museum' :3.5,
'The Transporter' :3.0,
'Social Network' :4.5,
'Paranormal Activity'  :3.5},
 
'JUde':
 {'Shawshank Redemption' :4.5,
'Star Wars' :4.0,
'50 Shades of Grey' :3.5,
'The Imitation Game' :3.0,
'Insidious' :3.0,
'Taken series' :3.5,
'Saw Series' :3.0,
'American Sniper' :4.0,
'Titanic' :4.5,
'Harry Potter Series' :5.0,
'Black Swan' :3.5,
'21 Jump Street' :3.5,
'Fight Club' :4.0,
'Braveheart'  :3.5,
'Lone Survivor' :3.5,
'Horrible Bosses'  :3.5,
'Lord of the Rings' :4.5,
'Sex Tape' :3.0,
'Ouija' :4.0,
'Frozen' :4.0,
'Finding Nemo' :4.5,
'Night at the Museum' :3.0,
'The Transporter' :4.0,
'Social Network' :3.5,
'Paranormal Activity'  :4.0},
 
'Arun':
 {'Shawshank Redemption' :3.5,
'Star Wars' :3.0,
'50 Shades of Grey' :2.5,
'The Imitation Game' :3.0,
'Insidious' :3.0,
'Taken series' :3.0,
'Saw Series' :3.0,
'American Sniper' :3.0,
'Titanic' :3.5,
'Harry Potter Series' :2.0,
'Black Swan' :3.0,
'21 Jump Street' :3.5,
'Fight Club' :3.5,
'Braveheart'  :3.5,
'Lone Survivor' :3.0,
'Horrible Bosses'  :2.5,
'Lord of the Rings' :3.5,
'Sex Tape' :2.0,
'Ouija' :2.5,
'Frozen' :3.0,
'Finding Nemo' :3.5,
'Night at the Museum' :3.0,
'The Transporter' :3.0,
'Social Network' :2.5,
'Paranormal Activity'  :2.0},
 
'Karthik':
 {'Shawshank Redemption' :4.5,
'Star Wars' :3.0,
'50 Shades of Grey' :4.5,
'The Imitation Game' :4.5,
'Insidious' :5.0,
'Taken series' :4.5,
'Saw Series' :5.0,
'American Sniper' :4.5,
'Titanic' :5.0,
'Harry Potter Series' :4.5,
'Black Swan' :5.0,
'21 Jump Street' :5.0,
'Fight Club' :5.0,
'Braveheart'  :3.0,
'Lone Survivor' :4.5,
'Horrible Bosses'  :4.5,
'Lord of the Rings' :5.0,
'Sex Tape' :3.0,
'Ouija' :3.0,
'Frozen' :3.5,
'Finding Nemo' :4.0,
'Night at the Museum' :5.0,
'The Transporter' :4.0,
'Social Network' :4.0,
'Paranormal Activity'  :4.5},
 
'Bass':
 {'Shawshank Redemption' :4.5,
'Star Wars' :3.0,
'50 Shades of Grey' :2.5,
'The Imitation Game' :1.5,
'Insidious' :3.0,
'Taken series' :3.5,
'Saw Series' :3.0,
'American Sniper' :3.5,
'Titanic' :4.0,
'Harry Potter Series' :4.0,
'Black Swan' :4.0,
'21 Jump Street' :3.5,
'Fight Club' :4.5,
'Braveheart'  :4.0,
'Lone Survivor' :3.5,
'Horrible Bosses'  :4.0,
'Lord of the Rings' :4.0,
'Sex Tape' :3.0,
'Ouija' :3.0,
'Frozen' :3.0,
'Finding Nemo' :3.0,
'Night at the Museum' :3.0,
'The Transporter' :3.0,
'Social Network' :3.0,
'Paranormal Activity'  :3.0},
 
'Devika':
 {'Shawshank Redemption' :5.0,
'Star Wars' :4.0,
'50 Shades of Grey' :5.0,
'The Imitation Game' :3.5,
'Insidious' :2.5,
'Taken series' :2.5,
'Saw Series' :2.0,
'American Sniper' :2.5,
'Titanic' :3.5,
'Harry Potter Series' :4.5,
'Black Swan' :4.0,
'21 Jump Street' :3.0,
'Fight Club' :2.5,
'Braveheart'  :4.0,
'Lone Survivor' :3.0,
'Horrible Bosses'  :2.5,
'Lord of the Rings' :4.0,
'Sex Tape' :2.0,
'Ouija' :1.5,
'Frozen' :3.5,
'Finding Nemo' :4.0,
'Night at the Museum' :1.0,
'The Transporter' :3.0,
'Social Network' :4.0,
'Paranormal Activity'  :3.0},
 
'Gappa':
 {'Shawshank Redemption' :5.0,
'Star Wars' :5.0,
'50 Shades of Grey' :5.0,
'The Imitation Game' :4.5,
'Insidious' :5.0,
'Taken series' :5.0,
'Saw Series' :4.5,
'American Sniper' :5.0,
'Titanic' :5.0,
'Harry Potter Series' :5.0,
'Black Swan' :4.5,
'21 Jump Street' :5.0,
'Fight Club' :5.0,
'Braveheart'  :5.0,
'Lone Survivor' :4.5,
'Horrible Bosses'  :5.0,
'Lord of the Rings' :5.0,
'Sex Tape' :5.0,
'Ouija' :3.5,
'Frozen' :3.5,
'Finding Nemo' :4.0,
'Night at the Museum' :4.5,
'The Transporter' :5.0,
'Social Network' :5.0,
'Paranormal Activity'  :4.5},
 
'Aravind':
 {'Shawshank Redemption' :2.5,
'Star Wars' :2.5,
'50 Shades of Grey' :2.5,
'The Imitation Game' :3.0,
'Insidious' :3.5,
'Taken series' :3.5,
'Saw Series' :4.0,
'American Sniper' :2.0,
'Titanic' :3.5,
'Harry Potter Series' :3.5,
'Black Swan' :3.0,
'21 Jump Street' :4.0,
'Fight Club' :3.5,
'Braveheart'  :3.0,
'Lone Survivor' :3.0,
'Horrible Bosses'  :4.0,
'Lord of the Rings' :4.0,
'Sex Tape' :3.0,
'Ouija' :2.5,
'Frozen' :3.5,
'Finding Nemo' :4.0,
'Night at the Museum' :4.0,
'The Transporter' :4.0,
'Social Network' :2.5,
'Paranormal Activity'  :3.5},
 
'Krishanth':
 {'Shawshank Redemption' :5.0,
'Star Wars' :4.5,
'50 Shades of Grey' :1.0,
'The Imitation Game' :4.0,
'Insidious' :2.5,
'Taken series' :3.5,
'Saw Series' :3.0,
'American Sniper' :4.5,
'Titanic' :4.5,
'Harry Potter Series' :4.5,
'Black Swan' :3.5,
'21 Jump Street' :3.5,
'Fight Club' :4.0,
'Lord of the Rings' :4.5,
'Ouija' :3.0,
'Frozen' :4.0,
'Finding Nemo' :4.0,
'Night at the Museum' :3.5,
'The Transporter' :3.5,
'Social Network' :3.5,
'Paranormal Activity'  :4.5},
 
'Karthik':
 {'Shawshank Redemption' :4.5,
'Star Wars' :5.0,
'50 Shades of Grey' :1.5,
'The Imitation Game' :4.5,
'Insidious' :4.0,
'Taken series' :3.0,
'Saw Series' :3.5,
'American Sniper' :4.0,
'Titanic' :4.0,
'Harry Potter Series' :4.0,
'Black Swan' :4.0,
'21 Jump Street' :2.5,
'Fight Club' :4.0,
'Braveheart'  :5.0,
'Lone Survivor' :2.5,
'Horrible Bosses'  :2.5,
'Lord of the Rings' :3.5,
'Sex Tape' :1.0,
'Ouija' :1.0,
'Frozen' :2.5,
'Finding Nemo' :3.5,
'Night at the Museum' :3.0,
'The Transporter' :3.5,
'Social Network' :3.5,
'Paranormal Activity'  :3.0},
 
'Akshay':
 {'Shawshank Redemption' :5.0,
'Star Wars' :2.0,
'50 Shades of Grey' :2.5,
'The Imitation Game' :4.5,
'Insidious' :3.0,
'Taken series' :3.5,
'Saw Series' :4.5,
'American Sniper' :5.0,
'Titanic' :1.5,
'Harry Potter Series' :2.5,
'Black Swan' :4.0,
'21 Jump Street' :4.0,
'Fight Club' :3.0,
'Braveheart'  :4.5,
'Lone Survivor' :4.5,
'Horrible Bosses'  :4.0,
'Lord of the Rings' :3.0,
'Sex Tape' :4.0,
'Ouija' :4.5,
'Frozen' :5.0,
'Finding Nemo' :2.5,
'Night at the Museum' :2.5,
'The Transporter' :4.5,
'Social Network' :3.5},
 
'Eeshaan':
 {'Shawshank Redemption' :4.5,
'Star Wars' :4.0,
'50 Shades of Grey' :1.0,
'The Imitation Game' :4.0,
'Insidious' :2.0,
'Taken series' :1.5,
'Saw Series' :2.0,
'American Sniper' :4.5,
'Titanic' :4.0,
'Harry Potter Series' :4.0,
'Black Swan' :3.5,
'21 Jump Street' :4.0,
'Fight Club' :4.0,
'Braveheart'  :4.5,
'Lone Survivor' :3.5,
'Lord of the Rings' :4.0,
'Sex Tape' :2.5,
'Ouija' :2.0,
'Frozen' :2.5,
'Finding Nemo' :3.0,
'Night at the Museum' :3.0,
'The Transporter' :3.0,
'Social Network' :4.0,
'Paranormal Activity'  :2.5},
 
'Harish':
 {'Shawshank Redemption' :4.5,
'Star Wars' :2.0,
'50 Shades of Grey' :3.0,
'The Imitation Game' :5.0,
'Insidious' :3.0,
'Taken series' :3.5,
'Saw Series' :4.5,
'American Sniper' :4.5,
'Titanic' :2.0,
'Harry Potter Series' :2.5,
'Black Swan' :3.5,
'21 Jump Street' :4.0,
'Fight Club' :4.5,
'Braveheart'  :5.0,
'Lone Survivor' :4.0,
'Horrible Bosses'  :3.5,
'Lord of the Rings' :2.0,
'Sex Tape' :2.0,
'Ouija' :3.5,
'Frozen' :4.5,
'Finding Nemo' :1.5,
'Night at the Museum' :1.5,
'The Transporter' :3.5,
'Social Network' :4.0,
'Paranormal Activity'  :3.0},
 
'Thalajay':
 {'Shawshank Redemption' :5.0,
'Star Wars' :4.0,
'50 Shades of Grey' :2.0,
'The Imitation Game' :4.0,
'Insidious' :3.0,
'Taken series' :2.5,
'Saw Series' :1.5,
'American Sniper' :3.5,
'Titanic' :4.5,
'Harry Potter Series' :5.0,
'Black Swan' :3.5,
'21 Jump Street' :3.0,
'Fight Club' :3.0,
'Braveheart'  :2.5,
'Horrible Bosses'  :3.0,
'Lord of the Rings' :4.5,
'Sex Tape' :2.5,
'Ouija' :1.5,
'Frozen' :3.5,
'Finding Nemo' :3.0,
'Night at the Museum' :2.5,
'The Transporter' :3.5,
'Social Network' :4.5,
'Paranormal Activity'  :2.0},
 
'Avinash':
 {'Shawshank Redemption' :5.0,
'Star Wars' :4.0,
'50 Shades of Grey' :3.0,
'The Imitation Game' :4.5,
'Insidious' :3.5,
'Taken series' :4.0,
'Saw Series' :4.0,
'American Sniper' :3.5,
'Titanic' :5.0,
'Harry Potter Series' :5.0,
'Black Swan' :3.5,
'21 Jump Street' :4.5,
'Fight Club' :4.5,
'Braveheart'  :3.5,
'Lone Survivor' :4.0,
'Horrible Bosses'  :4.5,
'Lord of the Rings' :4.5,
'Sex Tape' :4.0,
'Ouija' :4.0,
'Frozen' :4.5,
'Finding Nemo' :4.5,
'Night at the Museum' :3.5,
'The Transporter' :4.0,
'Social Network' :4.0,
'Paranormal Activity'  :3.0}}
